name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        required: true      

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ github.event.inputs.name }}"
